import exceptions 
class DataJointError(exceptions.Exception):
    pass